version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  # Map the frontend port to host

  backend:
    build: ./backend
    ports:
      - "8080:8080"  # Map the backend port to host
